# Image de base
FROM node:18-alpine

# Dossier de travail dans le container
WORKDIR /app

# Copier les fichiers de configuration
COPY package*.json ./

# Installer les dépendances
RUN npm install --production

# Copier le code du backend
COPY . .

# Exposer le port backend
EXPOSE 5000

# Lancer l’application
CMD ["node", "app.js"]
